/*
** Copyright 2024 Double Precision, Inc.
a** See COPYING for distribution information.
*/
#include "config.h"
#include "proc_loader.H"
#include "messages.H"
#include "yaml_writer.H"
#include "parsed_yaml.H"
#include "privrequest.H"
#include <functional>
#include <string>
#include <fstream>
#include <set>
#include <optional>
#include <memory>
#include <algorithm>

void proc_get_environconfig(
	const std::function<void (const std::string &)> &error
)
{
	environconfigvars.clear();

	auto configfile=environconfig();

	std::ifstream input_file{configfile};

	if (!input_file)
	{
		error(configfile + ": " + strerror(errno));
		return;
	}

	yaml_parser_info info{input_file};

	if (!info.initialized)
	{
		error(configfile +
		      _(": YAML parser initialization failure"));

		return;
	}

	parsed_yaml parsed{info, configfile, error};

	if (!parsed.initialized)
	{
		return;
	}

	if (!parsed.parse_map(
		    yaml_document_get_root_node(&parsed.doc),
		    true,
		    configfile,
		    [&]
		    (const std::string &key,
		     yaml_node_t *n,
		     const auto &error)
		    {
			    std::unordered_set<std::string> aliases;

			    auto s=parsed.parse_scalar(n, configfile, error);

			    if (!s)
				    return false;

			    environconfigvars[key]=std::move(*s);

			    return true;
		    },
		    error))
	{
		environconfigvars.clear();
	}
}

void proc_set_environconfig(
	std::string key,
	std::optional<std::string> value,
	const std::function<void (const std::string &)> &error
)
{
	if (value)
	{
		environconfigvars[key]=std::move(*value);
	}
	else
	{
		environconfigvars.erase(key);
	}

	proc_set_environconfig(environconfig(), error);
}

void proc_set_environconfig(
	std::string configfile,
	const std::function<void (const std::string &)> &error
)
{
	std::string tmpname = configfile + "~";

	std::ofstream o{tmpname};

	if (!o)
	{
		error(tmpname + ": " + strerror(errno));
		return;
	}

	o << "# This file gets automatically updated.\n"
		"# Do not edit this file manually.\n\n";

	yaml_writer writer{o};

	if (!writer.initialized)
	{
		error(_("unable to initialize the YAML writer"));
		return;
	}

	yaml_map_t m;

	m.reserve(environconfigvars.size());

	for (auto &[name, value]:environconfigvars)
	{
		m.emplace_back(std::make_shared<yaml_write_scalar>(name),
			       std::make_shared<yaml_write_scalar>(value));
	}

	yaml_write_map env_vars{ std::move(m) };

	errno=0;

	if (!writer.write(env_vars) || (o.close(), !o) ||
	    rename(tmpname.c_str(), configfile.c_str()))
	{
		error(configfile + ": "
		      + (errno ? strerror(errno)
			 : _("error writing out the YAML file")));
	}
}
