#! /usr/bin/perl
#
# Modify /etc/rc.d/rc.K on the fly.
#
# Comment out "killall". The containers already took care of it, and it'll
# kill vera's public process.
#
# Comment out call to telinit
#
# Also comment out "sleep 1"s, that serve no purpose any more

use strict;
use warnings;

use IO::File;

my ($RCK) = @ARGV;

my $fh = IO::File->new($RCK, "r");

my $l;

while (defined($l = <$fh>))
{
    # Don't run killall. We stopped the containers ourselves
    $l =~ s/^killall/#/;

    # The sleep is not needed
    $l =~ s@sleep 1@true@;

    # Don't run telinit. We're on top of it.
    $l =~ s@^/sbin/telinit@#@;

    print $l;
}
